### ISSUE TITLE
[BUG] - Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by rainwashed** [chibisafe/chibisafe#361]
I am trying to run my own chibisafe instance with the Docker method (just a note, I have not really ever used Docker and so followed the instructions in the docs)

I got ``Illegal instruction (core dumped)`` error with ``docker_chibisafe_1 exited with code 132``. I only used the CLI tool provided in the project (the .sh file) and did everything the docs stated. 

I am running this on my Ubuntu Server 22.04 with Docker 20.10.22 and docker-compose 1.29.2.
![image](https://user-images.githubusercontent.com/60084007/212581048-c3e9a184-b371-495b-9f73-f8b52aacbc0d.png)

Forgive my ignorance if this issue was caused by my own wrong-doing.

**Comment by Pitu** [comment]
I've never encountered that issue before. I'll investigate a bit but honestly speaking I can't say I'll be able to provide a solution for you.

**Comment by rainwashed** [comment]
That is fine; thank you for trying

**Comment by verymilan** [comment]
Isn't this pointing to an unsupported processor architecture?

**Comment by Pitu** [comment]
@rainwashed could you provide more information on the server this is running on?

**Comment by rainwashed** [comment]
@Pitu 

``uname -a``
```
Linux [name]-hpdelltower 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
``sudo lscpu``
```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         48 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  3
  On-line CPU(s) list:   0-2
Vendor ID:               AuthenticAMD
  Model name:            AMD Phenom(tm) 8600B Triple-Core Processor
    CPU family:          16
    Model:               2
    Thread(s) per core:  1
    Core(s) per socket:  3
    Socket(s):           1
    Stepping:            3
    CPU max MHz:         2300.0000
    CPU min MHz:         1150.0000
    BogoMIPS:            4588.58
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse ss
                         e2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl no
                         nstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy a
                         bm sse4a misalignsse 3dnowprefetch osvw ibs hw_pstate vmmcall npt lbrv svm_lock
Virtualization features:
  Virtualization:        AMD-V
Caches (sum of all):
  L1d:                   192 KiB (3 instances)
  L1i:                   192 KiB (3 instances)
  L2:                    1.5 MiB (3 instances)
  L3:                    6 MiB (3 instances)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-2
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Not affected
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Not affected
  Tsx async abort:       Not affected
  ```
  ``neofetch``
```
OS: Ubuntu 22.04.1 LTS x86_64
Host: HP Compaq dc5850 Microtower
Kernel: 5.15.0-58-generic
Uptime: 3 mins
Packages: 835 (dpkg), 4 (snap)
Shell: bash 5.1.16
Terminal: /dev/pts/0
CPU: AMD Phenom 8600B Triple- (3) @ 2.300GHz
GPU: NVIDIA GeForce 210
Memory: 266MiB / 3908MiB
```

**Comment by ArakiSatoshi** [comment]
I have the same issue. I'm going through the setup process on the main page, as follows:

# curl https://get.volta.sh | bash
# volta install node
# mkdir chibisafe && cd chibisafe && wget https://link && unzip master.zip && cd chibisafe-master
# npm i
# npm run setup

And at the last command, the terminal greets me with the following message:

```
> chibisafe@4.0.2 migrate /home/dangan/chibisafe/chibisafe-master
> knex migrate:latest

Illegal instruction (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 132
npm ERR! chibisafe@4.0.2 migrate: `knex migrate:latest`
npm ERR! Exit status 132
npm ERR!
npm ERR! Failed at the chibisafe@4.0.2 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dangan/.npm/_logs/2023-05-13T01_47_50_426Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 132
npm ERR! chibisafe@4.0.2 setup: `node src/setup.js && npm run migrate && npm run seed`
npm ERR! Exit status 132
npm ERR!
npm ERR! Failed at the chibisafe@4.0.2 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dangan/.npm/_logs/2023-05-13T01_47_50_565Z-debug.log
```

cat /home/dangan/.npm/_logs/2023-05-13T01_47_50_426Z-debug.log :

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/dangan/.volta/tools/image/node/14.17.0/bin/node',
1 verbose cli   '/home/dangan/.volta/tools/image/node/14.17.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'migrate'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'premigrate', 'migrate', 'postmigrate' ]
5 info lifecycle chibisafe@4.0.2~premigrate: chibisafe@4.0.2
6 info lifecycle chibisafe@4.0.2~migrate: chibisafe@4.0.2
7 verbose lifecycle chibisafe@4.0.2~migrate: unsafe-perm in lifecycle true
8 verbose lifecycle chibisafe@4.0.2~migrate: PATH: /home/dangan/.volta/tools/image/node/14.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dangan/chibisafe/chibisafe-master/node_modules/.bin:/home/dangan/.volta/tools/image/node/14.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dangan/chibisafe/chibisafe-master/node_modules/.bin:/home/dangan/.volta/tools/image/node/14.17.0/bin:/home/dangan/.volta/bin:/home/dangan/.volta/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle chibisafe@4.0.2~migrate: CWD: /home/dangan/chibisafe/chibisafe-master
10 silly lifecycle chibisafe@4.0.2~migrate: Args: [ '-c', 'knex migrate:latest' ]
11 silly lifecycle chibisafe@4.0.2~migrate: Returned: code: 132  signal: null
12 info lifecycle chibisafe@4.0.2~migrate: Failed to exec migrate script
13 verbose stack Error: chibisafe@4.0.2 migrate: `knex migrate:latest`
13 verbose stack Exit status 132
13 verbose stack     at EventEmitter.<anonymous> (/home/dangan/.volta/tools/image/node/14.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/dangan/.volta/tools/image/node/14.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid chibisafe@4.0.2
15 verbose cwd /home/dangan/chibisafe/chibisafe-master
16 verbose Linux 5.15.0-71-generic
17 verbose argv "/home/dangan/.volta/tools/image/node/14.17.0/bin/node" "/home/dangan/.volta/tools/image/node/14.17.0/bin/npm" "run" "migrate"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 132
22 error chibisafe@4.0.2 migrate: `knex migrate:latest`
22 error Exit status 132
23 error Failed at the chibisafe@4.0.2 migrate script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 132, true ]
```

cat /home/dangan/.npm/_logs/2023-05-13T01_47_50_565Z-debug.log :

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/dangan/.volta/tools/image/node/14.17.0/bin/node',
1 verbose cli   '/home/dangan/.volta/tools/image/node/14.17.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'setup'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle chibisafe@4.0.2~presetup: chibisafe@4.0.2
6 info lifecycle chibisafe@4.0.2~setup: chibisafe@4.0.2
7 verbose lifecycle chibisafe@4.0.2~setup: unsafe-perm in lifecycle true
8 verbose lifecycle chibisafe@4.0.2~setup: PATH: /home/dangan/.volta/tools/image/node/14.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dangan/chibisafe/chibisafe-master/node_modules/.bin:/home/dangan/.volta/tools/image/node/14.17.0/bin:/home/dangan/.volta/bin:/home/dangan/.volta/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle chibisafe@4.0.2~setup: CWD: /home/dangan/chibisafe/chibisafe-master
10 silly lifecycle chibisafe@4.0.2~setup: Args: [ '-c', 'node src/setup.js && npm run migrate && npm run seed' ]
11 silly lifecycle chibisafe@4.0.2~setup: Returned: code: 132  signal: null
12 info lifecycle chibisafe@4.0.2~setup: Failed to exec setup script
13 verbose stack Error: chibisafe@4.0.2 setup: `node src/setup.js && npm run migrate && npm run seed`
13 verbose stack Exit status 132
13 verbose stack     at EventEmitter.<anonymous> (/home/dangan/.volta/tools/image/node/14.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/dangan/.volta/tools/image/node/14.17.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid chibisafe@4.0.2
15 verbose cwd /home/dangan/chibisafe/chibisafe-master
16 verbose Linux 5.15.0-71-generic
17 verbose argv "/home/dangan/.volta/tools/image/node/14.17.0/bin/node" "/home/dangan/.volta/tools/image/node/14.17.0/bin/npm" "run" "setup"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 132
22 error chibisafe@4.0.2 setup: `node src/setup.js && npm run migrate && npm run seed`
22 error Exit status 132
23 error Failed at the chibisafe@4.0.2 setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 132, true ]
```

There are a couple of warnings when I run "npm i" that might be worth noting:

```
npm WARN eslint-plugin-vue@5.2.3 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN vue-eslint-parser@5.0.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN chibisafe@4.0.2 scripts['tests'] should probably be scripts['test'].
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules/@nuxt/builder/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules/@nuxt/components/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/sass/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

sudo lscpu:

```
Architecture:           x86_64
  CPU op-mode(s):       32-bit, 64-bit
  Address sizes:        36 bits physical, 48 bits virtual
  Byte Order:           Little Endian
CPU(s):                 4
  On-line CPU(s) list:  0-3
Vendor ID:              GenuineIntel
  Model name:           Intel(R) Atom(TM) CPU N2800   @ 1.86GHz
    CPU family:         6
    Model:              54
    Thread(s) per core: 2
    Core(s) per socket: 2
    Socket(s):          1
    Stepping:           1
    CPU max MHz:        1862.0000
    CPU min MHz:        798.0000
    BogoMIPS:           3733.18
    Flags:              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clfl
                        ush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_
                        perfmon pebs bts nopl nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl
                         est tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm arat
Caches (sum of all):
  L1d:                  48 KiB (2 instances)
  L1i:                  64 KiB (2 instances)
  L2:                   1 MiB (2 instances)
NUMA:
  NUMA node(s):         1
  NUMA node0 CPU(s):    0-3
Vulnerabilities:
  Itlb multihit:        Not affected
  L1tf:                 Not affected
  Mds:                  Not affected
  Meltdown:             Not affected
  Mmio stale data:      Not affected
  Retbleed:             Not affected
  Spec store bypass:    Not affected
  Spectre v1:           Not affected
  Spectre v2:           Not affected
  Srbds:                Not affected
  Tsx async abort:      Not affected
```

**Comment by ayuinaba** [comment]
Currently having the exact same issue, no idea how to fix it. I'm a complete noob at this, hence why I followed this guide: https://blog.rapph.dev/guide-chibisafe/

`uname -a`

```
Linux 6.1.0-0.deb11.6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.15-1~bpo11+1 (2023-03-16) x86_64 GNU/Linux
```

My processor might be too old for this? No idea.

```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           15
Model name:                      Intel(R) Core(TM)2 CPU          4300  @ 1.80GHz
Stepping:                        2
CPU MHz:                         1203.608
CPU max MHz:                     1800.0000
CPU min MHz:                     1200.0000
```

`neofetch`

```
OS: Debian GNU/Linux 11 (bullseye) x86_64 
Kernel: 6.1.0-0.deb11.6-amd64 
Uptime: 1 day, 11 mins 
Packages: 542 (dpkg) 
Shell: bash 5.1.4 
Resolution: 1920x1080 
Terminal: /dev/pts/0 
CPU: Intel Core 2 4300 (2) @ 1.800GHz 
GPU: NVIDIA GeForce 7800 GT 
Memory: 652MiB / 4865MiB
```

docker-compose file I used to deploy chibisafe (from the repository in the guide I used):

```
version: "3.7"

networks: #Add to my Nginx Network in Docker. Just makes life easier for me, and you may need to change this depending on what reverse proxy you are using.
    default:
        external:
            name: "swag_default"

services:
    chibisafe:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: ayuinaba/chibisafe #Tag Docker Image
        container_name: chibisafe #Name container name
        volumes:
            - /chibisafe/data:/usr/chibisafe/uploads
            - /chibisafe/database:/usr/chibisafe/database
        ports: #You still should have a reverse proxy pointing to the container. Connecting to it through localhost or any other means might/will probably give you issues.
            - 5051:5000
        hostname: chibisafe
        restart: unless-stopped
        environment:
            OVERWRITE_SETTINGS: "true"
            CHUNK_SIZE: 90
            ROUTE_PREFIX: /api
            RATE_LIMIT_WINDOW: 2
            RATE_LIMIT_MAX: 5
            SECRET: #"" <--- "openssl rand -base64 32" To Generate.
            MAX_LINKS_PER_ALBUM: 5
            META_THEME_COLOR: "#20222b"
            META_DESCRIPTION: "Blazing fast file uploader!🚀"
            META_KEYWORDS: "chibisafe,upload,uploader,file,vue,images,ssr,file uploader"
            META_TWITTER_HANDLE: ""
            BLOCKED_EXTENSIONS: ".msi"
            SERVER_PORT: 5000
            DOMAIN: "[my domain]" #Change this to the domain you are hosting this on or you will get network errors when trying to login.
            SERVICE_NAME: ayusafe
            MAX_SIZE: 72727
            GENERATE_THUMBNAILS: "true"
            GENERATE_ZIPS: "true"
            STRIP_EXIF: "true" #Recommended to keep true.
            SERVE_WITH_NODE: "true"
            GENERATED_FILENAME_LENGTH: 10
            GENERATED_ALBUM_LENGTH: 6
            PUBLIC_MODE: "false"
            USER_ACCOUNTS: "true"
            ADMIN_ACCOUNT: #"admin"
            ADMIN_PASSWORD: #"admin"
            DB_CLIENT: "sqlite3" #You probably should be running a external DB, but there is one already part of the container. Also there is an issue with Chibisafe duplicating db entries in docker, but seems to work fine in production.
            DB_HOST: ""
            DB_USER: ""
            DB_PASSWORD: ""
            DB_DATABASE: ""
```

I added the ADMIN_ACCOUNT, ADMIN_PASSWORD and SECRET variables on Portainer.
