### ISSUE TITLE
Can't upload anything, getting "TypeError: globalThis.crypto.randomUUID is not a function"

### ISSUE THREAD

**Issue by Nesvet** [chibisafe/chibisafe#472]
Hi! Thanks for this awesome stuff!

I've just made a clean install of version `5.2.4` via docker compose:

```
version: "3.7"
name: chibisafe

services:
  
  chibisafe:
    container_name: chibisafe
    image: chibisafe/chibisafe:latest
    environment:
      - TZ
    volumes:
      - ${DIR}/database:/home/node/chibisafe/database:rw
      - ${DIR}/uploads:/home/node/chibisafe/uploads:rw
      - ${DIR}/logs:/home/node/chibisafe/logs:rw
    ports:
      - ${PORT}:8000
    restart: always
```

On upload I'm getting nothing but the error in the console:
```
index.9e74e0ac.js:757 Uncaught (in promise) TypeError: globalThis.crypto.randomUUID is not a function
    at z0 (index.9e74e0ac.js:757:71987)
    at x (index.9e74e0ac.js:759:50875)
    at P (index.9e74e0ac.js:759:51704)
    at d.value.V.onChange.T.<computed>.T.<computed> (index.9e74e0ac.js:759:53160)
    at hn (index.9e74e0ac.js:1:14111)
    at Mt (index.9e74e0ac.js:1:14190)
    at HTMLInputElement.n (index.9e74e0ac.js:1:57851)
```
