### ISSUE TITLE
[BUG] Trying to download any file results in 404

### ISSUE THREAD

**Issue by epicylon** [chibisafe/chibisafe#608]
I'm a bit slow when it comes to file hosting, so please forgive me in advance.

I've ran V.5 without issues, and only started facing issues after upgrading to V.6. I didn't migrate, but started a fresh instance.

I use Cloudflare tunnels to access my  `https://cdn.example.com`, where I host Chibisafe.

Every file I try to upload will result in a 404. Now, I have tried multiple options in `Serve Uploads From` at `dashboard/admin/settings`, including just leaving it blank. _What am I actually supposed to put there?_

**docker-compose.yml**
```
version: "3.7"

services:
  chibisafe:
    image: chibisafe/chibisafe:latest
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
    expose:
      - 8001
    restart: unless-stopped

  chibisafe_server:
    image: chibisafe/chibisafe-server:latest
    volumes:
      - ./database:/app/database:rw
      - /srv/dev-disk-by-uuid-fb356deb-b84e-4804-80ff-e8522de72f07/downloads/send:/app/uploads:rw
      - ./logs:/app/logs:rw
    expose:
      - 8000
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./uploads:/app/uploads:ro
    ports:
      - 24424:80
    environment:
      - BASE_URL=":80"
    restart: unless-stopped
```

**Caddyfile**
```
{
        servers {
                trusted_proxies static private_ranges
                client_ip_headers X-Forwarded-For X-Real-IP
        }
}

{$BASE_URL} {
        route {
                file_server * {
                        root /app/uploads
                        pass_thru
                }

                @api path /api/*
                reverse_proxy @api http://chibisafe_server:8000 {
                        header_up Host {http.reverse_proxy.upstream.hostport}
                        header_up X-Real-IP {http.request.header.X-Real-IP}
                }

                @docs path /docs*
                reverse_proxy @docs http://chibisafe_server:8000 {
                        header_up Host {http.reverse_proxy.upstream.hostport}
                        header_up X-Real-IP {http.request.header.X-Real-IP}
```
