### ISSUE TITLE
[BUG] TypeError: r is undefined

### ISSUE THREAD

**Issue by FuckingToasters** [chibisafe/chibisafe#673]
**Describe the bug**
After i successfully setup the chibisafe service on my domain and tried to login with the default credentials (user: admin, pass: admin) i got a error inside a white box relativly at the bottom of the screen which included following text: `TypeError: r is undefined`.

Here the compose file i used:
```yml
version: '3.0'

services:
  chibisafe:
    container_name: chibisafe
    image: chibisafe/chibisafe:latest
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
    networks:
      - revproxy
    restart: unless-stopped

  chibisafe_server:
    container_name: chibisafe_server
    image: chibisafe/chibisafe-server:latest
    volumes:
      - chibisafe_database:/app/database:rw
      - chibisafe_uploads:/app/uploads:rw
      - chibisafe_logs:/app/logs:rw
    networks:
      - revproxy
    restart: unless-stopped

  caddy-chibsafe:
    container_name: caddy-chibisafe
    image: caddy:2-alpine
    volumes:
      - chibisafe_caddy:/etc/caddy:ro
      - chibisafe_uploads:/app/uploads:ro
    networks:
      - revproxy
    environment:
      - BASE_URL=":80"
    restart: unless-stopped
    

volumes:
  chibisafe_database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/chibisafe_database
  chibisafe_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/chibisafe_uploads
  chibisafe_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/chibisafe_logs
  chibisafe_caddy:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/chibisafe_caddy

networks:
  revproxy:
    external: true
```

**To Reproduce**
1. Use the compose file provided to setup chibisafe
2. Add chibisafe to a domain via nginx proxy manager
3. Press the `Get Started` Button and then login with the default admin credentials

**Expected behavior**
I expected it to log me in successfully without any error.

**Screenshots**
![grafik](https://github.com/chibisafe/chibisafe/assets/94435104/c5a9cccd-3c24-4f63-bcb6-ed360b32d369)

**Additional context**
I checked the logs from all 3 related services (caddy-chibisafe, chibisafe & chibisafe_server. None of those show any warning or error.
