### ISSUE TITLE
[BUG] Login Submittion routes to wrong url

### ISSUE THREAD

**Issue by FuckingToasters** [chibisafe/chibisafe#675]
**Describe the bug**
I have my cibisafe running on https://chibisafe.vbucksgenerator.zip and the API Server on https://chibiserver.vbucksgenerator.zip
When i try to login while specting network traffic (Browser Dev Tools) i see that a post request with the provided credentials is being made to https://chibisafe.vbucksgenerator.zip/api/auth/login instead of chibiserver.

the logs of the api server show following:
```
[11:32:48.513] INFO (143): Running Chibisafe v6.4.2
[11:32:48.966] WARN (143): Found route without URL or METHOD - dist/routes/admin            /files/Unzip.js
[11:32:49.267] WARN (143): Found route without URL or METHOD - dist/routes/album            /ZipAlbum.js
[11:32:49.665] INFO (143): Server listening at http://0.0.0.0:8000
[11:32:50.590] INFO (143): No updates available
```

Compose file:
```yml
version: '3.0'

services:
  chibisafe:
    container_name: chibisafe
    image: chibisafe/chibisafe:latest
    environment:
      - BASE_API_URL=https://chibiserver.vbucksgenerator.zip
    expose:
      - 8001
    networks:
      - revproxy
    restart: unless-stopped

  chibisafe_server:
    container_name: chibisafe_server
    image: chibisafe/chibisafe-server:latest
    volumes:
      - chibisafe_database:/app/database:rw
      - chibisafe_uploads:/app/uploads:rw
      - chibisafe_logs:/app/logs:rw
    expose:
      - 8000
    networks:
      - revproxy
    restart: unless-stopped

  caddy-chibsafe:
    container_name: caddy-chibisafe
    image: caddy:2-alpine
    volumes:
      - /docker/chibisafe_caddyfile/Caddyfile:/etc/caddy/Caddyfile:ro
      - chibisafe_uploads:/app/uploads:ro
    networks:
      - revproxy
    ports:
      - 24424:80
    environment:
      - BASE_URL=":80"
    restart: unless-stopped
    

volumes:
  chibisafe_database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/chibisafe_database
  chibisafe_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/chibisafe_uploads
  chibisafe_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /docker/chibisafe_logs

networks:
  revproxy:
    external: true
```

**To Reproduce**
1. Setup chbisafe with the docker compose file provided above
2. Point the VPS IP to a proxied cloudflare subdomain
3. In Nginx Proxy Manager, add the cloudflare letsencrypt ssl certificates and proxyhosts
4. Configure the enviroment variable baseurl of chibisafe to use chibiserver (as shown in the composefile above)
5. try to login while having devtools open.
6. see typerror: r is not defined and 404 as api response statuscode

**Expected behavior**
I expected everything to work flawlessly

**Screenshots**
![grafik](https://github.com/chibisafe/chibisafe/assets/94435104/4ad3e899-6927-4de6-b08f-56d90bb8e680)
![grafik](https://github.com/chibisafe/chibisafe/assets/94435104/3ca94986-e307-4e07-b682-65bb68891c38)

**Additional context**
nothing
