### ISSUE TITLE
[BUG] login TypeError: r is undefined via nginx proxy manager

### ISSUE THREAD

**Issue by DerMerten** [chibisafe/chibisafe#679]
**Describe the bug**
I use the version with nginx proxy manager. I have just set it up but I get the following error message TypeError: r is undefined (see screenshot) I have logged in with the default login data. 

i used this guide: https://chibisafe.app/guides/running-with-nginx-proxy-manager 

this is my docker-compose.yml:
```
version: "3.7"
services:
  chibisafe:
    image: chibisafe/chibisafe:latest
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
    expose:
      - 8001
    restart: unless-stopped
    ports:
      - 8001:8001

  chibisafe_server:
    image: chibisafe/chibisafe-server:latest
    volumes:
      - ./database:/app/database:rw
      - ./uploads:/app/uploads:rw
      - ./logs:/app/logs:rw
    expose:
      - 8002
    restart: unless-stopped
    ports:
      - 8002:8000
   ```
**Screenshots**
![image](https://github.com/chibisafe/chibisafe/assets/90412698/a43972ec-cd16-4c61-bb9b-e601c830d2ed)
