### ISSUE TITLE
[BUG] container starts and runs, but no UI

### ISSUE THREAD

**Issue by cinghialino** [chibisafe/chibisafe#699]
**Describe the bug**

after following the instruction, the container starts but no starting page is reacheable. (This page isn’t working
[my internal IP] didn’t send any data.
ERR_EMPTY_RESPONSE )

Please help

**To Reproduce**
I have a Synology NAS with Portainer
Went into Stacks and pasted this there:
```
services:
  chibisafe:
    image: chibisafe/chibisafe:latest
    container_name: chibisafe
    volumes:
      - /volume1/docker/chibisafe/database:/home/node/chibisafe/database:rw
      - /volume1/docker/chibisafe/uploads:/home/node/chibisafe/uploads:rw
      - ./volume1/docker/chibisafe/logs:/home/node/chibisafe/logs:rw
    ports:
      - 24424:8000
    restart: always
```
the folders exists.

**Expected behavior**

**Screenshots**

**Additional context**
