### ISSUE TITLE
[BUG] "No authorization header provided" error on public upload setup

### ISSUE THREAD

**Issue by ivancarlosti** [chibisafe/chibisafe#705]
**Describe the bug**
When open the website to upload files using not logged account, I get the message "No authorization header provided".
This error do not happens when I disable Public Mode.

**To Reproduce**
1. Enable Public Mode
2. Open the site font page
3. See error

**Expected behavior**
A front page without error

**Screenshots**
![image](https://github.com/user-attachments/assets/d7a6efe9-c494-4f9e-a779-bc54ff4c5ef2)

**Additional context**
Uploads works fine, the only problem is the error popping up on front page. I use nginx on host (not docked) as reverse proxy for docker websites. I already tried to redirect nginx to Caddy with same issue, now I am connecting directly to chibisafe (host:8001) and /api, /docs (host:8000)

My docker compose file:

```
name: envio

services:
  chibisafe:
    image: chibisafe/chibisafe:latest
    container_name: envio
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
    expose:
      - 8001
    ports:
      - 8001:8001
    restart: unless-stopped

  chibisafe_server:
    image: chibisafe/chibisafe-server:latest
    container_name: envio-server
    volumes:
      - ./database:/app/database:rw
      - ./uploads:/app/uploads:rw
      - ./logs:/app/logs:rw
    expose:
      - 8000
    ports:
      - 8000:8000
    restart: unless-stopped
```

My nginx setup:

```
server {
  listen 80;
  listen [::]:80;
  listen 443 quic;
  listen 443 ssl;
  listen [::]:443 quic;
  listen [::]:443 ssl;
  http2 on;
  http3 on;
  {{ssl_certificate_key}}
  {{ssl_certificate}}
  server_name <host>;
  {{root}}

  {{nginx_access_log}}
  {{nginx_error_log}}

  if ($scheme != "https") {
    rewrite ^ https://$host$request_uri permanent;
  }

###################
  location /api {
    proxy_pass http://127.0.0.1:8000;
  }

  location /docs {
    proxy_pass http://127.0.0.1:8000;
  }
###################

  location @reverse_proxy {
    proxy_pass {{reverse_proxy_url}};
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_pass_request_headers on;
    proxy_max_temp_file_size 0;
    proxy_connect_timeout 900;
    proxy_send_timeout 900;
    proxy_read_timeout 900;
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
    proxy_temp_file_write_size 256k;
  }

  {{settings}}

  include /etc/nginx/global_settings;

  add_header Cache-Control no-transform;

  index index.html;

  location ^~ /.well-known {
    auth_basic off;
    allow all;
    try_files $uri @reverse_proxy;
  }

  location / {
    try_files $uri @reverse_proxy;
  }
}
```
